<a href="https://colab.research.google.com/github/senBenz/TP2/blob/main/Exerccice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
myindex = ['CANADA','USA','FRANCE','UK']
mycolumns = ['Jan','Feb','Mar']
dframe=pd.DataFrame(mydata,index=myindex,columns=mycolumns)
print(dframe)

        Jan  Feb  Mar
CANADA   95   11   81
USA      70   63   87
FRANCE   75    9   77
UK       40    4   63

### Explication
Cette cellule initialise un DataFrame pandas `dframe` avec des valeurs entières aléatoires comprises entre 0 et 100. Les lignes représentent des pays et les colonnes les mois de janvier à mars.

In [7]:
print(dframe.describe())

             Jan        Feb        Mar
count   4.000000   4.000000   4.000000
mean   70.000000  21.750000  77.000000
std    22.730303  27.657127  10.198039
min    40.000000   4.000000  63.000000
25%    62.500000   7.750000  73.500000
50%    72.500000  10.000000  79.000000
75%    80.000000  24.000000  82.500000
max    95.000000  63.000000  87.000000

### Explication
La méthode `.describe()` génère des statistiques descriptives (moyenne, écart-type, min, max, quartiles) pour chaque colonne numérique du DataFrame.

In [8]:
dframe.drop('FRANCE')

        Jan  Feb  Mar
CANADA   95   11   81
USA      70   63   87
UK       40    4   63

### Explication
L'opération `.drop('FRANCE')` renvoie une copie du DataFrame sans la ligne 'FRANCE'. Notez que sans l'argument `inplace=True`, le DataFrame original `dframe` reste inchangé.

In [14]:
dframe.loc['USA']

Jan    70
Feb    63
Mar    87
Name: USA, dtype: int64

### Explication
L'attribut `.loc['USA']` est utilisé pour sélectionner et afficher toutes les données relatives à la ligne 'USA' sous forme de Série.

In [16]:
dframe.loc[:,'Jan']

CANADA    95
USA       70
FRANCE    75
UK        40
Name: Jan, dtype: int64

### Explication
Ici, `.loc[:,'Jan']` permet de sélectionner l'intégralité de la colonne 'Jan' pour tous les pays présents dans l'index.