<a href="https://colab.research.google.com/github/senBenz/TP2/blob/main/Exercice3ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

Cette cellule permet de monter votre Google Drive pour accéder aux fichiers qui y sont stockés.

In [4]:
import pandas as pd

file_path = '/content/drive/MyDrive/movie_scores.csv'
df = pd.read_csv(file_path)
display(df.head())

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

On charge le fichier CSV dans un DataFrame pandas et on affiche les 5 premières lignes pour inspecter les données.

In [ ]:
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

La méthode `isnull()` retourne un booléen pour chaque cellule : `True` si la donnée est manquante (NaN), `False` sinon.

In [10]:
df['first_name'].dropna()

0      Tom
2     Hugh
3    Oprah
4     Emma
Name: first_name, dtype: object

Ici, on extrait la colonne 'first_name' en supprimant les valeurs nulles, ce qui permet de ne garder que les prénoms valides.

In [12]:
df['post_movie_score'].sort_values(ascending=False).dropna()

0    10.0
4     9.0
3     8.0
Name: post_movie_score, dtype: float64

Cette commande trie les scores par ordre décroissant et élimine les valeurs manquantes pour identifier les meilleures performances.

In [13]:
df.fillna('Nouvelle_valeur')

,first_name,last_name,age,sex,pre_movie_score,post_movie_score
0,Tom,Hanks,63.0,m,8.0,10.0
1,Nouvelle_valeur,Nouvelle_valeur,Nouvelle_valeur,Nouvelle_valeur,Nouvelle_valeur,Nouvelle_valeur
2,Hugh,Jackman,51.0,m,Nouvelle_valeur,Nouvelle_valeur
3,Oprah,Winfrey,66.0,f,6.0,8.0
4,Emma,Stone,31.0,f,7.0,9.0

`fillna()` est utilisé pour remplacer toutes les valeurs manquantes par un texte par défaut, évitant ainsi les calculs sur des données vides.

In [33]:
df.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

`dropna(axis='columns')` supprime toute colonne contenant au moins une valeur nulle. Comme une ligne est entièrement vide dans ce dataset, toutes les colonnes ont été supprimées.