<a href="https://colab.research.google.com/github/senBenz/TP2/blob/TP3/TP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [41]:
import pandas as pd
file_path='/content/drive/MyDrive/retail_synthetique_tp3.csv'
df=pd.read_csv(file_path)
df.head()

,date,ville,magasin,transaction_id,client_id,sexe,age_client,categorie,produit,prix_unitaire,quantite,remise_pct,moyen_paiement
0,2024-06-12,Marrakech,D,T000001,C1177,F,42.0,Vetements,Sweat,761.72,2,15.0,Especes
1,2024-12-29,Fes,B,T000002,C1067,M,41.0,Alimentation,The,151.93,1,0.0,Especes
2,2024-06-24,Marrakech,A,T000003,C1216,M,27.0,Alimentation,Pates,99.02,1,0.0,Carte
3,2024-02-26,Marrakech,E,T000004,C1028,F,52.0,Maison,Coussin,835.89,1,10.0,Carte
4,2024-04-21,Marrakech,B,T000005,C1654,M,35.0,Beaute,Shampooing,666.02,3,10.0,Especes

In [42]:
df=df[['date','produit','prix_unitaire','quantite']]

In [43]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1n8aMAu1caM5RI4gnpmzb63pM_9HFDRvaIEvn2N2iowY/edit#gid=0

# Q1- les colonnes ci dessus sont les colonnes qui vont nous aider a repondre aux questions du client et pour atteindre les objectifs

In [44]:
df['date'] = pd.to_datetime(df['date'])
df['is_dimanche']=df['date'].dt.day_name()
df

           date     produit  prix_unitaire  quantite is_dimanche
0    2024-06-12       Sweat         761.72         2   Wednesday
1    2024-12-29         The         151.93         1      Sunday
2    2024-06-24       Pates          99.02         1      Monday
3    2024-02-26     Coussin         835.89         1      Monday
4    2024-04-21  Shampooing         666.02         3      Sunday
...         ...         ...            ...       ...         ...
3510 2024-11-08     T-shirt         685.12         2      Friday
3511 2024-03-29      Souris        1481.26         1      Friday
3512 2024-11-01     Clavier        1646.68         1      Friday
3513 2024-07-24  Smartphone        2357.40         1   Wednesday
3514 2024-06-24        Jean         148.98         1      Monday

[3515 rows x 5 columns]

# l'ajout d'une nouvelle colonne is_dimanche qui va contenir les jours du semaine

In [45]:
df['is_dimanche'] = df['is_dimanche'].map({'Sunday': 'dimanche'}).fillna('autres_jours')
df.head()

        date     produit  prix_unitaire  quantite   is_dimanche
0 2024-06-12       Sweat         761.72         2  autres_jours
1 2024-12-29         The         151.93         1      dimanche
2 2024-06-24       Pates          99.02         1  autres_jours
3 2024-02-26     Coussin         835.89         1  autres_jours
4 2024-04-21  Shampooing         666.02         3      dimanche

# Q2, on a constituer  deux sous-ensembles : Dimanche / Autres jours.

In [46]:
print(df.iloc[0:2])

        date produit  prix_unitaire  quantite   is_dimanche
0 2024-06-12   Sweat         761.72         2  autres_jours
1 2024-12-29     The         151.93         1      dimanche

# Q3- chaque ligne pour ette anaylse sera comptee comme transaction car avec les donnes present il est claire que nous representons des transactions