<a href="https://colab.research.google.com/github/senBenz/TP2/blob/TP3/TP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [47]:
import pandas as pd
file_path='/content/drive/MyDrive/retail_synthetique_tp3.csv'
df=pd.read_csv(file_path)
df.head()

,date,ville,magasin,transaction_id,client_id,sexe,age_client,categorie,produit,prix_unitaire,quantite,remise_pct,moyen_paiement
0,2024-06-12,Marrakech,D,T000001,C1177,F,42.0,Vetements,Sweat,761.72,2,15.0,Especes
1,2024-12-29,Fes,B,T000002,C1067,M,41.0,Alimentation,The,151.93,1,0.0,Especes
2,2024-06-24,Marrakech,A,T000003,C1216,M,27.0,Alimentation,Pates,99.02,1,0.0,Carte
3,2024-02-26,Marrakech,E,T000004,C1028,F,52.0,Maison,Coussin,835.89,1,10.0,Carte
4,2024-04-21,Marrakech,B,T000005,C1654,M,35.0,Beaute,Shampooing,666.02,3,10.0,Especes

In [48]:
df=df[['date','produit','prix_unitaire','quantite','ville','moyen_paiement','remise_pct']]

In [49]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/170t542IHSoL42WKoUtxYc2bk9r0Pe0F6o-2-HOZ99yY/edit#gid=0

# Q1- les colonnes ci dessus sont les colonnes qui vont nous aider a repondre aux questions du client et pour atteindre les objectifs

In [50]:
df['date'] = pd.to_datetime(df['date'])
df['is_dimanche']=df['date'].dt.day_name()
df

,date,produit,prix_unitaire,quantite,ville,moyen_paiement,remise_pct,is_dimanche
0,2024-06-12,Sweat,761.72,2,Marrakech,Especes,15.0,Wednesday
1,2024-12-29,The,151.93,1,Fes,Especes,0.0,Sunday
2,2024-06-24,Pates,99.02,1,Marrakech,Carte,0.0,Monday
3,2024-02-26,Coussin,835.89,1,Marrakech,Carte,10.0,Monday
4,2024-04-21,Shampooing,666.02,3,Marrakech,Especes,10.0,Sunday
...,...,...,...,...,...,...,...,...
3510,2024-11-08,T-shirt,685.12,2,Rabat,Carte,5.0,Friday
3511,2024-03-29,Souris,1481.26,1,Marrakech,Carte,0.0,Friday
3512,2024-11-01,Clavier,1646.68,1,Fes,Carte,15.0,Friday
3513,2024-07-24,Smartphone,2357.40,1,Tanger,Carte,0.0,Wednesday
3514,2024-06-24,Jean,148.98,1,Agadir,En ligne,15.0,Monday

# l'ajout d'une nouvelle colonne is_dimanche qui va contenir les jours du semaine

In [51]:
df['is_dimanche'] = df['is_dimanche'].map({'Sunday': 'dimanche'}).fillna('autres_jours')
df.head()

,date,produit,prix_unitaire,quantite,ville,moyen_paiement,remise_pct,is_dimanche
0,2024-06-12,Sweat,761.72,2,Marrakech,Especes,15.0,autres_jours
1,2024-12-29,The,151.93,1,Fes,Especes,0.0,dimanche
2,2024-06-24,Pates,99.02,1,Marrakech,Carte,0.0,autres_jours
3,2024-02-26,Coussin,835.89,1,Marrakech,Carte,10.0,autres_jours
4,2024-04-21,Shampooing,666.02,3,Marrakech,Especes,10.0,dimanche

# Q2, on a constituer  deux sous-ensembles : Dimanche / Autres jours.

In [52]:
print(df.iloc[0:2])

        date produit  prix_unitaire  quantite      ville moyen_paiement  \
0 2024-06-12   Sweat         761.72         2  Marrakech        Especes
1 2024-12-29     The         151.93         1        Fes        Especes

   remise_pct   is_dimanche
0        15.0  autres_jours
1         0.0      dimanche

# Q3- chaque ligne pour ette anaylse sera comptee comme transaction car avec les donnes present il est claire que nous representons des transactions

In [53]:
df[df.duplicated()]

,date,produit,prix_unitaire,quantite,ville,moyen_paiement,remise_pct,is_dimanche
3500,2024-03-14,Tapis Yoga,587.27,1,Fes,En-ligne,0.0,autres_jours
3501,2024-06-23,T-shirt,644.86,1,Agadir,Carte,0.0,dimanche
3502,2024-11-09,Clavier,3133.11,1,Casablanca,Carte,0.0,autres_jours
3503,2024-10-02,Pates,200.41,2,Agadir,Especes,5.0,autres_jours
3504,2024-05-13,Veste,230.67,1,Agadir,Carte,0.0,autres_jours
3505,2024-10-20,The,34.73,1,Agadir,Carte,10.0,dimanche
3506,2024-03-25,Miroir,601.07,1,Fes,Carte,0.0,autres_jours
3507,2024-06-20,Chaussures Running,881.54,1,Marrakech,Especes,10.0,autres_jours
3508,2024-11-14,Tapis,385.03,1,Casablanca,Carte,0.0,autres_jours
3509,2024-10-31,Cafe,164.97,2,Casablanca,Carte,0.0,autres_jours
3510,2024-11-08,T-shirt,685.12,2,Rabat,Carte,5.0,autres_jours
3511,2024-03-29,Souris,1481.26,1,Marrakech,Carte,0.0,autres_jours
3512,2024-11-01,Clavier,1646.68,1,Fes,Carte,15.0,autres_jours
3513,2024-07-24,Smartphone,2357.40,1,Tanger,Carte,0.0,autres_jours
3514,2024-06-24,Jean,148.98,1,Agadir,En ligne,15.0,autres_jours

### Dans cette etape on a pu identifier le doublons qu'on a dasn le dataset

In [54]:
df.duplicated().sum()

np.int64(15)

Dans cette etape on a idientifier combien de duplicat on a qui est 15 duplicat

In [55]:
df.drop_duplicates()

,date,produit,prix_unitaire,quantite,ville,moyen_paiement,remise_pct,is_dimanche
0,2024-06-12,Sweat,761.72,2,Marrakech,Especes,15.0,autres_jours
1,2024-12-29,The,151.93,1,Fes,Especes,0.0,dimanche
2,2024-06-24,Pates,99.02,1,Marrakech,Carte,0.0,autres_jours
3,2024-02-26,Coussin,835.89,1,Marrakech,Carte,10.0,autres_jours
4,2024-04-21,Shampooing,666.02,3,Marrakech,Especes,10.0,dimanche
...,...,...,...,...,...,...,...,...
3495,2024-04-29,Savon,428.85,2,Rabat,Carte,0.0,autres_jours
3496,2024-09-22,Coussin,1161.92,2,Tanger,En ligne,5.0,dimanche
3497,2024-12-09,T-shirt,288.06,1,Tanger,Carte,10.0,autres_jours
3498,2024-01-14,Riz,165.44,2,Rabat,En ligne,0.0,dimanche
3499,2024-01-25,Table,364.42,2,Tanger,Carte,5.0,autres_jours

# Q4- on a detecter 15 duplicat et pour notre analyses ci ces dones sont redondant on peut les supprimer et c'est ce qu'on a fait a l'aide de la fonction drop_duplicates()

# Q5 , Q6 - afin d'arriver aux objectifs du client les donnees qu'on a sont **suffisant**

In [56]:
df['moyen_paiement'].replace({
    'CB':'Carte',
    'En-ligne':'En ligne'

})

0        Especes
1        Especes
2          Carte
3          Carte
4        Especes
          ...
3510       Carte
3511       Carte
3512       Carte
3513       Carte
3514    En ligne
Name: moyen_paiement, Length: 3515, dtype: object

In [57]:
df

,date,produit,prix_unitaire,quantite,ville,moyen_paiement,remise_pct,is_dimanche
0,2024-06-12,Sweat,761.72,2,Marrakech,Especes,15.0,autres_jours
1,2024-12-29,The,151.93,1,Fes,Especes,0.0,dimanche
2,2024-06-24,Pates,99.02,1,Marrakech,Carte,0.0,autres_jours
3,2024-02-26,Coussin,835.89,1,Marrakech,Carte,10.0,autres_jours
4,2024-04-21,Shampooing,666.02,3,Marrakech,Especes,10.0,dimanche
...,...,...,...,...,...,...,...,...
3510,2024-11-08,T-shirt,685.12,2,Rabat,Carte,5.0,autres_jours
3511,2024-03-29,Souris,1481.26,1,Marrakech,Carte,0.0,autres_jours
3512,2024-11-01,Clavier,1646.68,1,Fes,Carte,15.0,autres_jours
3513,2024-07-24,Smartphone,2357.40,1,Tanger,Carte,0.0,autres_jours
3514,2024-06-24,Jean,148.98,1,Agadir,En ligne,15.0,autres_jours

# Q7- on peut clairement voir que l'harmonisation du colonne moyen_paiement a ete effectuee

In [59]:
df['montant']=df['prix_unitaire']*df['quantite']*(1-(df['remise_pct']/100))

In [61]:
df['montant']

0       1294.924
1        151.930
2         99.020
3        752.301
4       1798.254
          ...
3510    1301.728
3511    1481.260
3512    1399.678
3513    2357.400
3514     126.633
Name: montant, Length: 3515, dtype: float64

# Q8- voici la colonne montant qui est calculee sous la formule suivante


```
montant = prix_unitaire × quantite × (1 − remise_pct/100).
```

In [76]:
import math
stats=0


def resume_statistiques(df, colonne):
    stats={
        'n ': len(df[colonne]),
        ' somme  ':float(df[colonne].sum()),
        'moyenn ':float(df[colonne].mean()),
        'median ':df[colonne].median(),
        'ecart_type ':math.sqrt(df[colonne].var()),
        'Q1 ':float(df[colonne].quantile(0.25)),
        'Q3 ':float(df[colonne].quantile(0.75)),
        'IQR ':float(df[colonne].quantile(0.75)-df[colonne].quantile(0.25))
    }
    return stats








print(resume_statistiques(df,'montant'))

{'n ': 3515, ' somme  ': 3431359.4524999997, 'moyenn ': 1006.5589476386036, 'median ': 569.41, 'ecart_type ': 1310.153480567198, 'Q1 ': 209.39999999999998, 'Q3 ': 1269.5895, 'IQR ': 1060.1895}

# Q9- résumé statistique de montant